name: Build Artifacts

on:
  push:
    branches:
      - '**'
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          cache-disabled: true
        
      - name: Build Spigot-Mapped
        uses: gradle/gradle-build-action@v3
        with:
          arguments: |
            loaderJarSpigot
            -PoutDir=artifacts
            -Prelease

      - name: Upload Artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: ./artifacts/*.jar

      - name: Deploy Mojang-Mapped
        if: github.event_name == 'release'
        uses: gradle/gradle-build-action@v3
        with:
          arguments: | 
            publishNovaPublicationToXenondevsRepository
            publishNovaAPIPublicationToXenondevsRepository
            publishNovaGradlePluginPublicationToXenondevsRepository
            publishNova-gradle-pluginPluginMarkerMavenPublicationToXenondevsRepository
            publishCatalogPublicationToXenondevsRepository
            -Prelease
        env:
          ORG_GRADLE_PROJECT_xenondevsUsername: ${{ secrets.XENONDEVS_RELEASES_USERNAME }}
          ORG_GRADLE_PROJECT_xenondevsPassword: ${{ secrets.XENONDEVS_RELEASES_PASSWORD }}
